[project]
name = "zfull-pixel-font"
version = "0.0.0"
requires-python = ">=3.14"

dependencies = [
    "pixel-font-builder==0.0.47",
    "fonttools[woff]==4.61.1",
    "loguru==0.7.3",
    "cyclopts==4.5.2",
]
